# Codecov configuration for aix
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "**/*_test.go"
  - "cmd/aix/main.go"
