// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandable creates a new instance of MockCommandable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandable {
	mock := &MockCommandable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandable is an autogenerated mock type for the Commandable type
type MockCommandable struct {
	mock.Mock
}

type MockCommandable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandable) EXPECT() *MockCommandable_Expecter {
	return &MockCommandable_Expecter{mock: &_m.Mock}
}

// GetName provides a mock function for the type MockCommandable
func (_mock *MockCommandable) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommandable_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockCommandable_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockCommandable_Expecter) GetName() *MockCommandable_GetName_Call {
	return &MockCommandable_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockCommandable_GetName_Call) Run(run func()) *MockCommandable_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandable_GetName_Call) Return(s string) *MockCommandable_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommandable_GetName_Call) RunAndReturn(run func() string) *MockCommandable_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// SetInstructions provides a mock function for the type MockCommandable
func (_mock *MockCommandable) SetInstructions(s string) {
	_mock.Called(s)
	return
}

// MockCommandable_SetInstructions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInstructions'
type MockCommandable_SetInstructions_Call struct {
	*mock.Call
}

// SetInstructions is a helper method to define mock.On call
//   - s string
func (_e *MockCommandable_Expecter) SetInstructions(s interface{}) *MockCommandable_SetInstructions_Call {
	return &MockCommandable_SetInstructions_Call{Call: _e.mock.On("SetInstructions", s)}
}

func (_c *MockCommandable_SetInstructions_Call) Run(run func(s string)) *MockCommandable_SetInstructions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommandable_SetInstructions_Call) Return() *MockCommandable_SetInstructions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommandable_SetInstructions_Call) RunAndReturn(run func(s string)) *MockCommandable_SetInstructions_Call {
	_c.Run(run)
	return _c
}

// SetName provides a mock function for the type MockCommandable
func (_mock *MockCommandable) SetName(s string) {
	_mock.Called(s)
	return
}

// MockCommandable_SetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetName'
type MockCommandable_SetName_Call struct {
	*mock.Call
}

// SetName is a helper method to define mock.On call
//   - s string
func (_e *MockCommandable_Expecter) SetName(s interface{}) *MockCommandable_SetName_Call {
	return &MockCommandable_SetName_Call{Call: _e.mock.On("SetName", s)}
}

func (_c *MockCommandable_SetName_Call) Run(run func(s string)) *MockCommandable_SetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommandable_SetName_Call) Return() *MockCommandable_SetName_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommandable_SetName_Call) RunAndReturn(run func(s string)) *MockCommandable_SetName_Call {
	_c.Run(run)
	return _c
}
