// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/thoreinstein/aix/internal/cli"
)

// NewMockPlatform creates a new instance of MockPlatform. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlatform(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlatform {
	mock := &MockPlatform{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlatform is an autogenerated mock type for the Platform type
type MockPlatform struct {
	mock.Mock
}

type MockPlatform_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlatform) EXPECT() *MockPlatform_Expecter {
	return &MockPlatform_Expecter{mock: &_m.Mock}
}

// AddMCP provides a mock function for the type MockPlatform
func (_mock *MockPlatform) AddMCP(server any, scope cli.Scope) error {
	ret := _mock.Called(server, scope)

	if len(ret) == 0 {
		panic("no return value specified for AddMCP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any, cli.Scope) error); ok {
		r0 = returnFunc(server, scope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_AddMCP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMCP'
type MockPlatform_AddMCP_Call struct {
	*mock.Call
}

// AddMCP is a helper method to define mock.On call
//   - server any
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) AddMCP(server interface{}, scope interface{}) *MockPlatform_AddMCP_Call {
	return &MockPlatform_AddMCP_Call{Call: _e.mock.On("AddMCP", server, scope)}
}

func (_c *MockPlatform_AddMCP_Call) Run(run func(server any, scope cli.Scope)) *MockPlatform_AddMCP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_AddMCP_Call) Return(err error) *MockPlatform_AddMCP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_AddMCP_Call) RunAndReturn(run func(server any, scope cli.Scope) error) *MockPlatform_AddMCP_Call {
	_c.Call.Return(run)
	return _c
}

// AgentDir provides a mock function for the type MockPlatform
func (_mock *MockPlatform) AgentDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AgentDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPlatform_AgentDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentDir'
type MockPlatform_AgentDir_Call struct {
	*mock.Call
}

// AgentDir is a helper method to define mock.On call
func (_e *MockPlatform_Expecter) AgentDir() *MockPlatform_AgentDir_Call {
	return &MockPlatform_AgentDir_Call{Call: _e.mock.On("AgentDir")}
}

func (_c *MockPlatform_AgentDir_Call) Run(run func()) *MockPlatform_AgentDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatform_AgentDir_Call) Return(s string) *MockPlatform_AgentDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPlatform_AgentDir_Call) RunAndReturn(run func() string) *MockPlatform_AgentDir_Call {
	_c.Call.Return(run)
	return _c
}

// BackupPaths provides a mock function for the type MockPlatform
func (_mock *MockPlatform) BackupPaths() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BackupPaths")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockPlatform_BackupPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackupPaths'
type MockPlatform_BackupPaths_Call struct {
	*mock.Call
}

// BackupPaths is a helper method to define mock.On call
func (_e *MockPlatform_Expecter) BackupPaths() *MockPlatform_BackupPaths_Call {
	return &MockPlatform_BackupPaths_Call{Call: _e.mock.On("BackupPaths")}
}

func (_c *MockPlatform_BackupPaths_Call) Run(run func()) *MockPlatform_BackupPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatform_BackupPaths_Call) Return(strings []string) *MockPlatform_BackupPaths_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockPlatform_BackupPaths_Call) RunAndReturn(run func() []string) *MockPlatform_BackupPaths_Call {
	_c.Call.Return(run)
	return _c
}

// CommandDir provides a mock function for the type MockPlatform
func (_mock *MockPlatform) CommandDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommandDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPlatform_CommandDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommandDir'
type MockPlatform_CommandDir_Call struct {
	*mock.Call
}

// CommandDir is a helper method to define mock.On call
func (_e *MockPlatform_Expecter) CommandDir() *MockPlatform_CommandDir_Call {
	return &MockPlatform_CommandDir_Call{Call: _e.mock.On("CommandDir")}
}

func (_c *MockPlatform_CommandDir_Call) Run(run func()) *MockPlatform_CommandDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatform_CommandDir_Call) Return(s string) *MockPlatform_CommandDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPlatform_CommandDir_Call) RunAndReturn(run func() string) *MockPlatform_CommandDir_Call {
	_c.Call.Return(run)
	return _c
}

// DisableMCP provides a mock function for the type MockPlatform
func (_mock *MockPlatform) DisableMCP(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for DisableMCP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_DisableMCP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableMCP'
type MockPlatform_DisableMCP_Call struct {
	*mock.Call
}

// DisableMCP is a helper method to define mock.On call
//   - name string
func (_e *MockPlatform_Expecter) DisableMCP(name interface{}) *MockPlatform_DisableMCP_Call {
	return &MockPlatform_DisableMCP_Call{Call: _e.mock.On("DisableMCP", name)}
}

func (_c *MockPlatform_DisableMCP_Call) Run(run func(name string)) *MockPlatform_DisableMCP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlatform_DisableMCP_Call) Return(err error) *MockPlatform_DisableMCP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_DisableMCP_Call) RunAndReturn(run func(name string) error) *MockPlatform_DisableMCP_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayName provides a mock function for the type MockPlatform
func (_mock *MockPlatform) DisplayName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DisplayName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPlatform_DisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayName'
type MockPlatform_DisplayName_Call struct {
	*mock.Call
}

// DisplayName is a helper method to define mock.On call
func (_e *MockPlatform_Expecter) DisplayName() *MockPlatform_DisplayName_Call {
	return &MockPlatform_DisplayName_Call{Call: _e.mock.On("DisplayName")}
}

func (_c *MockPlatform_DisplayName_Call) Run(run func()) *MockPlatform_DisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatform_DisplayName_Call) Return(s string) *MockPlatform_DisplayName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPlatform_DisplayName_Call) RunAndReturn(run func() string) *MockPlatform_DisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// EnableMCP provides a mock function for the type MockPlatform
func (_mock *MockPlatform) EnableMCP(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for EnableMCP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_EnableMCP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableMCP'
type MockPlatform_EnableMCP_Call struct {
	*mock.Call
}

// EnableMCP is a helper method to define mock.On call
//   - name string
func (_e *MockPlatform_Expecter) EnableMCP(name interface{}) *MockPlatform_EnableMCP_Call {
	return &MockPlatform_EnableMCP_Call{Call: _e.mock.On("EnableMCP", name)}
}

func (_c *MockPlatform_EnableMCP_Call) Run(run func(name string)) *MockPlatform_EnableMCP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlatform_EnableMCP_Call) Return(err error) *MockPlatform_EnableMCP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_EnableMCP_Call) RunAndReturn(run func(name string) error) *MockPlatform_EnableMCP_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgent provides a mock function for the type MockPlatform
func (_mock *MockPlatform) GetAgent(name string, scope cli.Scope) (any, error) {
	ret := _mock.Called(name, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetAgent")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) (any, error)); ok {
		return returnFunc(name, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) any); ok {
		r0 = returnFunc(name, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, cli.Scope) error); ok {
		r1 = returnFunc(name, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatform_GetAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgent'
type MockPlatform_GetAgent_Call struct {
	*mock.Call
}

// GetAgent is a helper method to define mock.On call
//   - name string
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) GetAgent(name interface{}, scope interface{}) *MockPlatform_GetAgent_Call {
	return &MockPlatform_GetAgent_Call{Call: _e.mock.On("GetAgent", name, scope)}
}

func (_c *MockPlatform_GetAgent_Call) Run(run func(name string, scope cli.Scope)) *MockPlatform_GetAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_GetAgent_Call) Return(v any, err error) *MockPlatform_GetAgent_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockPlatform_GetAgent_Call) RunAndReturn(run func(name string, scope cli.Scope) (any, error)) *MockPlatform_GetAgent_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommand provides a mock function for the type MockPlatform
func (_mock *MockPlatform) GetCommand(name string, scope cli.Scope) (any, error) {
	ret := _mock.Called(name, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetCommand")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) (any, error)); ok {
		return returnFunc(name, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) any); ok {
		r0 = returnFunc(name, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, cli.Scope) error); ok {
		r1 = returnFunc(name, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatform_GetCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommand'
type MockPlatform_GetCommand_Call struct {
	*mock.Call
}

// GetCommand is a helper method to define mock.On call
//   - name string
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) GetCommand(name interface{}, scope interface{}) *MockPlatform_GetCommand_Call {
	return &MockPlatform_GetCommand_Call{Call: _e.mock.On("GetCommand", name, scope)}
}

func (_c *MockPlatform_GetCommand_Call) Run(run func(name string, scope cli.Scope)) *MockPlatform_GetCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_GetCommand_Call) Return(v any, err error) *MockPlatform_GetCommand_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockPlatform_GetCommand_Call) RunAndReturn(run func(name string, scope cli.Scope) (any, error)) *MockPlatform_GetCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetMCP provides a mock function for the type MockPlatform
func (_mock *MockPlatform) GetMCP(name string, scope cli.Scope) (any, error) {
	ret := _mock.Called(name, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetMCP")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) (any, error)); ok {
		return returnFunc(name, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) any); ok {
		r0 = returnFunc(name, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, cli.Scope) error); ok {
		r1 = returnFunc(name, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatform_GetMCP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMCP'
type MockPlatform_GetMCP_Call struct {
	*mock.Call
}

// GetMCP is a helper method to define mock.On call
//   - name string
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) GetMCP(name interface{}, scope interface{}) *MockPlatform_GetMCP_Call {
	return &MockPlatform_GetMCP_Call{Call: _e.mock.On("GetMCP", name, scope)}
}

func (_c *MockPlatform_GetMCP_Call) Run(run func(name string, scope cli.Scope)) *MockPlatform_GetMCP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_GetMCP_Call) Return(v any, err error) *MockPlatform_GetMCP_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockPlatform_GetMCP_Call) RunAndReturn(run func(name string, scope cli.Scope) (any, error)) *MockPlatform_GetMCP_Call {
	_c.Call.Return(run)
	return _c
}

// GetSkill provides a mock function for the type MockPlatform
func (_mock *MockPlatform) GetSkill(name string, scope cli.Scope) (any, error) {
	ret := _mock.Called(name, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetSkill")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) (any, error)); ok {
		return returnFunc(name, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) any); ok {
		r0 = returnFunc(name, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, cli.Scope) error); ok {
		r1 = returnFunc(name, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatform_GetSkill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSkill'
type MockPlatform_GetSkill_Call struct {
	*mock.Call
}

// GetSkill is a helper method to define mock.On call
//   - name string
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) GetSkill(name interface{}, scope interface{}) *MockPlatform_GetSkill_Call {
	return &MockPlatform_GetSkill_Call{Call: _e.mock.On("GetSkill", name, scope)}
}

func (_c *MockPlatform_GetSkill_Call) Run(run func(name string, scope cli.Scope)) *MockPlatform_GetSkill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_GetSkill_Call) Return(v any, err error) *MockPlatform_GetSkill_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockPlatform_GetSkill_Call) RunAndReturn(run func(name string, scope cli.Scope) (any, error)) *MockPlatform_GetSkill_Call {
	_c.Call.Return(run)
	return _c
}

// InstallAgent provides a mock function for the type MockPlatform
func (_mock *MockPlatform) InstallAgent(agent any, scope cli.Scope) error {
	ret := _mock.Called(agent, scope)

	if len(ret) == 0 {
		panic("no return value specified for InstallAgent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any, cli.Scope) error); ok {
		r0 = returnFunc(agent, scope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_InstallAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallAgent'
type MockPlatform_InstallAgent_Call struct {
	*mock.Call
}

// InstallAgent is a helper method to define mock.On call
//   - agent any
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) InstallAgent(agent interface{}, scope interface{}) *MockPlatform_InstallAgent_Call {
	return &MockPlatform_InstallAgent_Call{Call: _e.mock.On("InstallAgent", agent, scope)}
}

func (_c *MockPlatform_InstallAgent_Call) Run(run func(agent any, scope cli.Scope)) *MockPlatform_InstallAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_InstallAgent_Call) Return(err error) *MockPlatform_InstallAgent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_InstallAgent_Call) RunAndReturn(run func(agent any, scope cli.Scope) error) *MockPlatform_InstallAgent_Call {
	_c.Call.Return(run)
	return _c
}

// InstallCommand provides a mock function for the type MockPlatform
func (_mock *MockPlatform) InstallCommand(cmd any, scope cli.Scope) error {
	ret := _mock.Called(cmd, scope)

	if len(ret) == 0 {
		panic("no return value specified for InstallCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any, cli.Scope) error); ok {
		r0 = returnFunc(cmd, scope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_InstallCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallCommand'
type MockPlatform_InstallCommand_Call struct {
	*mock.Call
}

// InstallCommand is a helper method to define mock.On call
//   - cmd any
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) InstallCommand(cmd interface{}, scope interface{}) *MockPlatform_InstallCommand_Call {
	return &MockPlatform_InstallCommand_Call{Call: _e.mock.On("InstallCommand", cmd, scope)}
}

func (_c *MockPlatform_InstallCommand_Call) Run(run func(cmd any, scope cli.Scope)) *MockPlatform_InstallCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_InstallCommand_Call) Return(err error) *MockPlatform_InstallCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_InstallCommand_Call) RunAndReturn(run func(cmd any, scope cli.Scope) error) *MockPlatform_InstallCommand_Call {
	_c.Call.Return(run)
	return _c
}

// InstallSkill provides a mock function for the type MockPlatform
func (_mock *MockPlatform) InstallSkill(skill any, scope cli.Scope) error {
	ret := _mock.Called(skill, scope)

	if len(ret) == 0 {
		panic("no return value specified for InstallSkill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any, cli.Scope) error); ok {
		r0 = returnFunc(skill, scope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_InstallSkill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallSkill'
type MockPlatform_InstallSkill_Call struct {
	*mock.Call
}

// InstallSkill is a helper method to define mock.On call
//   - skill any
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) InstallSkill(skill interface{}, scope interface{}) *MockPlatform_InstallSkill_Call {
	return &MockPlatform_InstallSkill_Call{Call: _e.mock.On("InstallSkill", skill, scope)}
}

func (_c *MockPlatform_InstallSkill_Call) Run(run func(skill any, scope cli.Scope)) *MockPlatform_InstallSkill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_InstallSkill_Call) Return(err error) *MockPlatform_InstallSkill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_InstallSkill_Call) RunAndReturn(run func(skill any, scope cli.Scope) error) *MockPlatform_InstallSkill_Call {
	_c.Call.Return(run)
	return _c
}

// IsAvailable provides a mock function for the type MockPlatform
func (_mock *MockPlatform) IsAvailable() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAvailable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPlatform_IsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailable'
type MockPlatform_IsAvailable_Call struct {
	*mock.Call
}

// IsAvailable is a helper method to define mock.On call
func (_e *MockPlatform_Expecter) IsAvailable() *MockPlatform_IsAvailable_Call {
	return &MockPlatform_IsAvailable_Call{Call: _e.mock.On("IsAvailable")}
}

func (_c *MockPlatform_IsAvailable_Call) Run(run func()) *MockPlatform_IsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatform_IsAvailable_Call) Return(b bool) *MockPlatform_IsAvailable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPlatform_IsAvailable_Call) RunAndReturn(run func() bool) *MockPlatform_IsAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// IsLocalConfigIgnored provides a mock function for the type MockPlatform
func (_mock *MockPlatform) IsLocalConfigIgnored() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsLocalConfigIgnored")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatform_IsLocalConfigIgnored_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLocalConfigIgnored'
type MockPlatform_IsLocalConfigIgnored_Call struct {
	*mock.Call
}

// IsLocalConfigIgnored is a helper method to define mock.On call
func (_e *MockPlatform_Expecter) IsLocalConfigIgnored() *MockPlatform_IsLocalConfigIgnored_Call {
	return &MockPlatform_IsLocalConfigIgnored_Call{Call: _e.mock.On("IsLocalConfigIgnored")}
}

func (_c *MockPlatform_IsLocalConfigIgnored_Call) Run(run func()) *MockPlatform_IsLocalConfigIgnored_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatform_IsLocalConfigIgnored_Call) Return(b bool, err error) *MockPlatform_IsLocalConfigIgnored_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPlatform_IsLocalConfigIgnored_Call) RunAndReturn(run func() (bool, error)) *MockPlatform_IsLocalConfigIgnored_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgents provides a mock function for the type MockPlatform
func (_mock *MockPlatform) ListAgents(scope cli.Scope) ([]cli.AgentInfo, error) {
	ret := _mock.Called(scope)

	if len(ret) == 0 {
		panic("no return value specified for ListAgents")
	}

	var r0 []cli.AgentInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(cli.Scope) ([]cli.AgentInfo, error)); ok {
		return returnFunc(scope)
	}
	if returnFunc, ok := ret.Get(0).(func(cli.Scope) []cli.AgentInfo); ok {
		r0 = returnFunc(scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cli.AgentInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(cli.Scope) error); ok {
		r1 = returnFunc(scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatform_ListAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgents'
type MockPlatform_ListAgents_Call struct {
	*mock.Call
}

// ListAgents is a helper method to define mock.On call
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) ListAgents(scope interface{}) *MockPlatform_ListAgents_Call {
	return &MockPlatform_ListAgents_Call{Call: _e.mock.On("ListAgents", scope)}
}

func (_c *MockPlatform_ListAgents_Call) Run(run func(scope cli.Scope)) *MockPlatform_ListAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cli.Scope
		if args[0] != nil {
			arg0 = args[0].(cli.Scope)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlatform_ListAgents_Call) Return(agentInfos []cli.AgentInfo, err error) *MockPlatform_ListAgents_Call {
	_c.Call.Return(agentInfos, err)
	return _c
}

func (_c *MockPlatform_ListAgents_Call) RunAndReturn(run func(scope cli.Scope) ([]cli.AgentInfo, error)) *MockPlatform_ListAgents_Call {
	_c.Call.Return(run)
	return _c
}

// ListCommands provides a mock function for the type MockPlatform
func (_mock *MockPlatform) ListCommands(scope cli.Scope) ([]cli.CommandInfo, error) {
	ret := _mock.Called(scope)

	if len(ret) == 0 {
		panic("no return value specified for ListCommands")
	}

	var r0 []cli.CommandInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(cli.Scope) ([]cli.CommandInfo, error)); ok {
		return returnFunc(scope)
	}
	if returnFunc, ok := ret.Get(0).(func(cli.Scope) []cli.CommandInfo); ok {
		r0 = returnFunc(scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cli.CommandInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(cli.Scope) error); ok {
		r1 = returnFunc(scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatform_ListCommands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCommands'
type MockPlatform_ListCommands_Call struct {
	*mock.Call
}

// ListCommands is a helper method to define mock.On call
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) ListCommands(scope interface{}) *MockPlatform_ListCommands_Call {
	return &MockPlatform_ListCommands_Call{Call: _e.mock.On("ListCommands", scope)}
}

func (_c *MockPlatform_ListCommands_Call) Run(run func(scope cli.Scope)) *MockPlatform_ListCommands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cli.Scope
		if args[0] != nil {
			arg0 = args[0].(cli.Scope)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlatform_ListCommands_Call) Return(commandInfos []cli.CommandInfo, err error) *MockPlatform_ListCommands_Call {
	_c.Call.Return(commandInfos, err)
	return _c
}

func (_c *MockPlatform_ListCommands_Call) RunAndReturn(run func(scope cli.Scope) ([]cli.CommandInfo, error)) *MockPlatform_ListCommands_Call {
	_c.Call.Return(run)
	return _c
}

// ListMCP provides a mock function for the type MockPlatform
func (_mock *MockPlatform) ListMCP(scope cli.Scope) ([]cli.MCPInfo, error) {
	ret := _mock.Called(scope)

	if len(ret) == 0 {
		panic("no return value specified for ListMCP")
	}

	var r0 []cli.MCPInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(cli.Scope) ([]cli.MCPInfo, error)); ok {
		return returnFunc(scope)
	}
	if returnFunc, ok := ret.Get(0).(func(cli.Scope) []cli.MCPInfo); ok {
		r0 = returnFunc(scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cli.MCPInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(cli.Scope) error); ok {
		r1 = returnFunc(scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatform_ListMCP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMCP'
type MockPlatform_ListMCP_Call struct {
	*mock.Call
}

// ListMCP is a helper method to define mock.On call
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) ListMCP(scope interface{}) *MockPlatform_ListMCP_Call {
	return &MockPlatform_ListMCP_Call{Call: _e.mock.On("ListMCP", scope)}
}

func (_c *MockPlatform_ListMCP_Call) Run(run func(scope cli.Scope)) *MockPlatform_ListMCP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cli.Scope
		if args[0] != nil {
			arg0 = args[0].(cli.Scope)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlatform_ListMCP_Call) Return(mCPInfos []cli.MCPInfo, err error) *MockPlatform_ListMCP_Call {
	_c.Call.Return(mCPInfos, err)
	return _c
}

func (_c *MockPlatform_ListMCP_Call) RunAndReturn(run func(scope cli.Scope) ([]cli.MCPInfo, error)) *MockPlatform_ListMCP_Call {
	_c.Call.Return(run)
	return _c
}

// ListSkills provides a mock function for the type MockPlatform
func (_mock *MockPlatform) ListSkills(scope cli.Scope) ([]cli.SkillInfo, error) {
	ret := _mock.Called(scope)

	if len(ret) == 0 {
		panic("no return value specified for ListSkills")
	}

	var r0 []cli.SkillInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(cli.Scope) ([]cli.SkillInfo, error)); ok {
		return returnFunc(scope)
	}
	if returnFunc, ok := ret.Get(0).(func(cli.Scope) []cli.SkillInfo); ok {
		r0 = returnFunc(scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cli.SkillInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(cli.Scope) error); ok {
		r1 = returnFunc(scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatform_ListSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSkills'
type MockPlatform_ListSkills_Call struct {
	*mock.Call
}

// ListSkills is a helper method to define mock.On call
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) ListSkills(scope interface{}) *MockPlatform_ListSkills_Call {
	return &MockPlatform_ListSkills_Call{Call: _e.mock.On("ListSkills", scope)}
}

func (_c *MockPlatform_ListSkills_Call) Run(run func(scope cli.Scope)) *MockPlatform_ListSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cli.Scope
		if args[0] != nil {
			arg0 = args[0].(cli.Scope)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlatform_ListSkills_Call) Return(skillInfos []cli.SkillInfo, err error) *MockPlatform_ListSkills_Call {
	_c.Call.Return(skillInfos, err)
	return _c
}

func (_c *MockPlatform_ListSkills_Call) RunAndReturn(run func(scope cli.Scope) ([]cli.SkillInfo, error)) *MockPlatform_ListSkills_Call {
	_c.Call.Return(run)
	return _c
}

// MCPConfigPath provides a mock function for the type MockPlatform
func (_mock *MockPlatform) MCPConfigPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MCPConfigPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPlatform_MCPConfigPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MCPConfigPath'
type MockPlatform_MCPConfigPath_Call struct {
	*mock.Call
}

// MCPConfigPath is a helper method to define mock.On call
func (_e *MockPlatform_Expecter) MCPConfigPath() *MockPlatform_MCPConfigPath_Call {
	return &MockPlatform_MCPConfigPath_Call{Call: _e.mock.On("MCPConfigPath")}
}

func (_c *MockPlatform_MCPConfigPath_Call) Run(run func()) *MockPlatform_MCPConfigPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatform_MCPConfigPath_Call) Return(s string) *MockPlatform_MCPConfigPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPlatform_MCPConfigPath_Call) RunAndReturn(run func() string) *MockPlatform_MCPConfigPath_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockPlatform
func (_mock *MockPlatform) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPlatform_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockPlatform_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockPlatform_Expecter) Name() *MockPlatform_Name_Call {
	return &MockPlatform_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockPlatform_Name_Call) Run(run func()) *MockPlatform_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatform_Name_Call) Return(s string) *MockPlatform_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPlatform_Name_Call) RunAndReturn(run func() string) *MockPlatform_Name_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMCP provides a mock function for the type MockPlatform
func (_mock *MockPlatform) RemoveMCP(name string, scope cli.Scope) error {
	ret := _mock.Called(name, scope)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMCP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) error); ok {
		r0 = returnFunc(name, scope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_RemoveMCP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMCP'
type MockPlatform_RemoveMCP_Call struct {
	*mock.Call
}

// RemoveMCP is a helper method to define mock.On call
//   - name string
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) RemoveMCP(name interface{}, scope interface{}) *MockPlatform_RemoveMCP_Call {
	return &MockPlatform_RemoveMCP_Call{Call: _e.mock.On("RemoveMCP", name, scope)}
}

func (_c *MockPlatform_RemoveMCP_Call) Run(run func(name string, scope cli.Scope)) *MockPlatform_RemoveMCP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_RemoveMCP_Call) Return(err error) *MockPlatform_RemoveMCP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_RemoveMCP_Call) RunAndReturn(run func(name string, scope cli.Scope) error) *MockPlatform_RemoveMCP_Call {
	_c.Call.Return(run)
	return _c
}

// SkillDir provides a mock function for the type MockPlatform
func (_mock *MockPlatform) SkillDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SkillDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPlatform_SkillDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SkillDir'
type MockPlatform_SkillDir_Call struct {
	*mock.Call
}

// SkillDir is a helper method to define mock.On call
func (_e *MockPlatform_Expecter) SkillDir() *MockPlatform_SkillDir_Call {
	return &MockPlatform_SkillDir_Call{Call: _e.mock.On("SkillDir")}
}

func (_c *MockPlatform_SkillDir_Call) Run(run func()) *MockPlatform_SkillDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatform_SkillDir_Call) Return(s string) *MockPlatform_SkillDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPlatform_SkillDir_Call) RunAndReturn(run func() string) *MockPlatform_SkillDir_Call {
	_c.Call.Return(run)
	return _c
}

// UninstallAgent provides a mock function for the type MockPlatform
func (_mock *MockPlatform) UninstallAgent(name string, scope cli.Scope) error {
	ret := _mock.Called(name, scope)

	if len(ret) == 0 {
		panic("no return value specified for UninstallAgent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) error); ok {
		r0 = returnFunc(name, scope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_UninstallAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UninstallAgent'
type MockPlatform_UninstallAgent_Call struct {
	*mock.Call
}

// UninstallAgent is a helper method to define mock.On call
//   - name string
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) UninstallAgent(name interface{}, scope interface{}) *MockPlatform_UninstallAgent_Call {
	return &MockPlatform_UninstallAgent_Call{Call: _e.mock.On("UninstallAgent", name, scope)}
}

func (_c *MockPlatform_UninstallAgent_Call) Run(run func(name string, scope cli.Scope)) *MockPlatform_UninstallAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_UninstallAgent_Call) Return(err error) *MockPlatform_UninstallAgent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_UninstallAgent_Call) RunAndReturn(run func(name string, scope cli.Scope) error) *MockPlatform_UninstallAgent_Call {
	_c.Call.Return(run)
	return _c
}

// UninstallCommand provides a mock function for the type MockPlatform
func (_mock *MockPlatform) UninstallCommand(name string, scope cli.Scope) error {
	ret := _mock.Called(name, scope)

	if len(ret) == 0 {
		panic("no return value specified for UninstallCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) error); ok {
		r0 = returnFunc(name, scope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_UninstallCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UninstallCommand'
type MockPlatform_UninstallCommand_Call struct {
	*mock.Call
}

// UninstallCommand is a helper method to define mock.On call
//   - name string
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) UninstallCommand(name interface{}, scope interface{}) *MockPlatform_UninstallCommand_Call {
	return &MockPlatform_UninstallCommand_Call{Call: _e.mock.On("UninstallCommand", name, scope)}
}

func (_c *MockPlatform_UninstallCommand_Call) Run(run func(name string, scope cli.Scope)) *MockPlatform_UninstallCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_UninstallCommand_Call) Return(err error) *MockPlatform_UninstallCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_UninstallCommand_Call) RunAndReturn(run func(name string, scope cli.Scope) error) *MockPlatform_UninstallCommand_Call {
	_c.Call.Return(run)
	return _c
}

// UninstallSkill provides a mock function for the type MockPlatform
func (_mock *MockPlatform) UninstallSkill(name string, scope cli.Scope) error {
	ret := _mock.Called(name, scope)

	if len(ret) == 0 {
		panic("no return value specified for UninstallSkill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, cli.Scope) error); ok {
		r0 = returnFunc(name, scope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_UninstallSkill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UninstallSkill'
type MockPlatform_UninstallSkill_Call struct {
	*mock.Call
}

// UninstallSkill is a helper method to define mock.On call
//   - name string
//   - scope cli.Scope
func (_e *MockPlatform_Expecter) UninstallSkill(name interface{}, scope interface{}) *MockPlatform_UninstallSkill_Call {
	return &MockPlatform_UninstallSkill_Call{Call: _e.mock.On("UninstallSkill", name, scope)}
}

func (_c *MockPlatform_UninstallSkill_Call) Run(run func(name string, scope cli.Scope)) *MockPlatform_UninstallSkill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 cli.Scope
		if args[1] != nil {
			arg1 = args[1].(cli.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_UninstallSkill_Call) Return(err error) *MockPlatform_UninstallSkill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_UninstallSkill_Call) RunAndReturn(run func(name string, scope cli.Scope) error) *MockPlatform_UninstallSkill_Call {
	_c.Call.Return(run)
	return _c
}
