// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/thoreinstein/aix/internal/mcp"
)

// NewMockTranslator creates a new instance of MockTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslator {
	mock := &MockTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranslator is an autogenerated mock type for the Translator type
type MockTranslator struct {
	mock.Mock
}

type MockTranslator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslator) EXPECT() *MockTranslator_Expecter {
	return &MockTranslator_Expecter{mock: &_m.Mock}
}

// FromCanonical provides a mock function for the type MockTranslator
func (_mock *MockTranslator) FromCanonical(cfg *mcp.Config) ([]byte, error) {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for FromCanonical")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*mcp.Config) ([]byte, error)); ok {
		return returnFunc(cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(*mcp.Config) []byte); ok {
		r0 = returnFunc(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*mcp.Config) error); ok {
		r1 = returnFunc(cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranslator_FromCanonical_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromCanonical'
type MockTranslator_FromCanonical_Call struct {
	*mock.Call
}

// FromCanonical is a helper method to define mock.On call
//   - cfg *mcp.Config
func (_e *MockTranslator_Expecter) FromCanonical(cfg interface{}) *MockTranslator_FromCanonical_Call {
	return &MockTranslator_FromCanonical_Call{Call: _e.mock.On("FromCanonical", cfg)}
}

func (_c *MockTranslator_FromCanonical_Call) Run(run func(cfg *mcp.Config)) *MockTranslator_FromCanonical_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mcp.Config
		if args[0] != nil {
			arg0 = args[0].(*mcp.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranslator_FromCanonical_Call) Return(bytes []byte, err error) *MockTranslator_FromCanonical_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockTranslator_FromCanonical_Call) RunAndReturn(run func(cfg *mcp.Config) ([]byte, error)) *MockTranslator_FromCanonical_Call {
	_c.Call.Return(run)
	return _c
}

// Platform provides a mock function for the type MockTranslator
func (_mock *MockTranslator) Platform() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Platform")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTranslator_Platform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Platform'
type MockTranslator_Platform_Call struct {
	*mock.Call
}

// Platform is a helper method to define mock.On call
func (_e *MockTranslator_Expecter) Platform() *MockTranslator_Platform_Call {
	return &MockTranslator_Platform_Call{Call: _e.mock.On("Platform")}
}

func (_c *MockTranslator_Platform_Call) Run(run func()) *MockTranslator_Platform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTranslator_Platform_Call) Return(s string) *MockTranslator_Platform_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTranslator_Platform_Call) RunAndReturn(run func() string) *MockTranslator_Platform_Call {
	_c.Call.Return(run)
	return _c
}

// ToCanonical provides a mock function for the type MockTranslator
func (_mock *MockTranslator) ToCanonical(platformData []byte) (*mcp.Config, error) {
	ret := _mock.Called(platformData)

	if len(ret) == 0 {
		panic("no return value specified for ToCanonical")
	}

	var r0 *mcp.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*mcp.Config, error)); ok {
		return returnFunc(platformData)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *mcp.Config); ok {
		r0 = returnFunc(platformData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mcp.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(platformData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranslator_ToCanonical_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToCanonical'
type MockTranslator_ToCanonical_Call struct {
	*mock.Call
}

// ToCanonical is a helper method to define mock.On call
//   - platformData []byte
func (_e *MockTranslator_Expecter) ToCanonical(platformData interface{}) *MockTranslator_ToCanonical_Call {
	return &MockTranslator_ToCanonical_Call{Call: _e.mock.On("ToCanonical", platformData)}
}

func (_c *MockTranslator_ToCanonical_Call) Run(run func(platformData []byte)) *MockTranslator_ToCanonical_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranslator_ToCanonical_Call) Return(config *mcp.Config, err error) *MockTranslator_ToCanonical_Call {
	_c.Call.Return(config, err)
	return _c
}

func (_c *MockTranslator_ToCanonical_Call) RunAndReturn(run func(platformData []byte) (*mcp.Config, error)) *MockTranslator_ToCanonical_Call {
	_c.Call.Return(run)
	return _c
}
