// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package doctor

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFixer creates a new instance of MockFixer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFixer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFixer {
	mock := &MockFixer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFixer is an autogenerated mock type for the Fixer type
type MockFixer struct {
	mock.Mock
}

type MockFixer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFixer) EXPECT() *MockFixer_Expecter {
	return &MockFixer_Expecter{mock: &_m.Mock}
}

// CanFix provides a mock function for the type MockFixer
func (_mock *MockFixer) CanFix() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanFix")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFixer_CanFix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanFix'
type MockFixer_CanFix_Call struct {
	*mock.Call
}

// CanFix is a helper method to define mock.On call
func (_e *MockFixer_Expecter) CanFix() *MockFixer_CanFix_Call {
	return &MockFixer_CanFix_Call{Call: _e.mock.On("CanFix")}
}

func (_c *MockFixer_CanFix_Call) Run(run func()) *MockFixer_CanFix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFixer_CanFix_Call) Return(b bool) *MockFixer_CanFix_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFixer_CanFix_Call) RunAndReturn(run func() bool) *MockFixer_CanFix_Call {
	_c.Call.Return(run)
	return _c
}

// Fix provides a mock function for the type MockFixer
func (_mock *MockFixer) Fix() []FixResult {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fix")
	}

	var r0 []FixResult
	if returnFunc, ok := ret.Get(0).(func() []FixResult); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]FixResult)
		}
	}
	return r0
}

// MockFixer_Fix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fix'
type MockFixer_Fix_Call struct {
	*mock.Call
}

// Fix is a helper method to define mock.On call
func (_e *MockFixer_Expecter) Fix() *MockFixer_Fix_Call {
	return &MockFixer_Fix_Call{Call: _e.mock.On("Fix")}
}

func (_c *MockFixer_Fix_Call) Run(run func()) *MockFixer_Fix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFixer_Fix_Call) Return(fixResults []FixResult) *MockFixer_Fix_Call {
	_c.Call.Return(fixResults)
	return _c
}

func (_c *MockFixer_Fix_Call) RunAndReturn(run func() []FixResult) *MockFixer_Fix_Call {
	_c.Call.Return(run)
	return _c
}
