// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package doctor

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCheck creates a new instance of MockCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheck {
	mock := &MockCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheck is an autogenerated mock type for the Check type
type MockCheck struct {
	mock.Mock
}

type MockCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheck) EXPECT() *MockCheck_Expecter {
	return &MockCheck_Expecter{mock: &_m.Mock}
}

// Category provides a mock function for the type MockCheck
func (_mock *MockCheck) Category() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Category")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCheck_Category_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Category'
type MockCheck_Category_Call struct {
	*mock.Call
}

// Category is a helper method to define mock.On call
func (_e *MockCheck_Expecter) Category() *MockCheck_Category_Call {
	return &MockCheck_Category_Call{Call: _e.mock.On("Category")}
}

func (_c *MockCheck_Category_Call) Run(run func()) *MockCheck_Category_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheck_Category_Call) Return(s string) *MockCheck_Category_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCheck_Category_Call) RunAndReturn(run func() string) *MockCheck_Category_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockCheck
func (_mock *MockCheck) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCheck_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockCheck_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockCheck_Expecter) Name() *MockCheck_Name_Call {
	return &MockCheck_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockCheck_Name_Call) Run(run func()) *MockCheck_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheck_Name_Call) Return(s string) *MockCheck_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCheck_Name_Call) RunAndReturn(run func() string) *MockCheck_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockCheck
func (_mock *MockCheck) Run() *CheckResult {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 *CheckResult
	if returnFunc, ok := ret.Get(0).(func() *CheckResult); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CheckResult)
		}
	}
	return r0
}

// MockCheck_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCheck_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockCheck_Expecter) Run() *MockCheck_Run_Call {
	return &MockCheck_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockCheck_Run_Call) Run(run func()) *MockCheck_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheck_Run_Call) Return(checkResult *CheckResult) *MockCheck_Run_Call {
	_c.Call.Return(checkResult)
	return _c
}

func (_c *MockCheck_Run_Call) RunAndReturn(run func() *CheckResult) *MockCheck_Run_Call {
	_c.Call.Return(run)
	return _c
}
