// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package validator

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentable creates a new instance of MockAgentable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentable {
	mock := &MockAgentable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentable is an autogenerated mock type for the Agentable type
type MockAgentable struct {
	mock.Mock
}

type MockAgentable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentable) EXPECT() *MockAgentable_Expecter {
	return &MockAgentable_Expecter{mock: &_m.Mock}
}

// GetDescription provides a mock function for the type MockAgentable
func (_mock *MockAgentable) GetDescription() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDescription")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAgentable_GetDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDescription'
type MockAgentable_GetDescription_Call struct {
	*mock.Call
}

// GetDescription is a helper method to define mock.On call
func (_e *MockAgentable_Expecter) GetDescription() *MockAgentable_GetDescription_Call {
	return &MockAgentable_GetDescription_Call{Call: _e.mock.On("GetDescription")}
}

func (_c *MockAgentable_GetDescription_Call) Run(run func()) *MockAgentable_GetDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgentable_GetDescription_Call) Return(s string) *MockAgentable_GetDescription_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAgentable_GetDescription_Call) RunAndReturn(run func() string) *MockAgentable_GetDescription_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstructions provides a mock function for the type MockAgentable
func (_mock *MockAgentable) GetInstructions() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInstructions")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAgentable_GetInstructions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstructions'
type MockAgentable_GetInstructions_Call struct {
	*mock.Call
}

// GetInstructions is a helper method to define mock.On call
func (_e *MockAgentable_Expecter) GetInstructions() *MockAgentable_GetInstructions_Call {
	return &MockAgentable_GetInstructions_Call{Call: _e.mock.On("GetInstructions")}
}

func (_c *MockAgentable_GetInstructions_Call) Run(run func()) *MockAgentable_GetInstructions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgentable_GetInstructions_Call) Return(s string) *MockAgentable_GetInstructions_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAgentable_GetInstructions_Call) RunAndReturn(run func() string) *MockAgentable_GetInstructions_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockAgentable
func (_mock *MockAgentable) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAgentable_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockAgentable_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockAgentable_Expecter) GetName() *MockAgentable_GetName_Call {
	return &MockAgentable_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockAgentable_GetName_Call) Run(run func()) *MockAgentable_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgentable_GetName_Call) Return(s string) *MockAgentable_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAgentable_GetName_Call) RunAndReturn(run func() string) *MockAgentable_GetName_Call {
	_c.Call.Return(run)
	return _c
}
